### ISSUE TITLE
Doesnt work with 1.2.20

### ISSUE THREAD

**Issue by aljawaid** [cdgeelen/kanboard_plugin_randomColorSelector#1]
I was expecting a button to change colors to random every time but this plugin doesnt do anything.

Any docs?

**Comment by cdgeelen** [comment]
Hello @aljawaid, unfortunately I can no longer assist. This plugin was written before v1.0.0 came out, thus most likely compatibility broke.

Feel free to use and modify this code as you'd like. 'll mark this repository as not maintained.
